.Dd 2 November 2010
.Dt WINCENT-ICON-UTIL \&1 "Wincent Icon Utility"
.Os Darwin
.Sh NAME
.Nm wincent-icon-util
.Nd apply a custom icon to a folder
.Sh SYNOPSIS
.Nm
.Ar -icon Ar icns-file          \" -icon icns-file
.Ar -target Ar target-folder    \" -target target-folder
.Sh DESCRIPTION
.Nm
applies the custom icon in
.Ar icns-file
to the folder
.Ar target-folder .
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl icon
Read custom icon from
.Ar icns-file .
.It Fl target
Apply custom icon to
.Ar target-folder .
.El
.Sh ERRORS
On encountering an error
.Nm
will print a description to standard error and exit with an exit code of 1.
.Sh SEE ALSO
.Xr GetFileInfo 1 ,
.Xr SetFile 1 ,
.Xr Rez 1
.Sh AUTHORS
.An "Wincent Colaiuta"
.Po
.Ad http://wincent.com/
.Pc
.Sh LICENSE
Wincent Icon Utility is copyright 2007-2010 Wincent Colaiuta.
.Pp
Wincent Icon Utility is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.Pp
Wincent Icon Utility is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
.Pp
You should have received a copy of the GNU General Public License along with Wincent Icon Utility.  If not, see <http://www.gnu.org/licenses/>.